
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from 'next/font/google'
import LogoutButton from "@/components/logout";
import ProviderComponent from "@/components/provider/provider";

const lato = Poppins({
  subsets: ['latin'],
  weight: ['100','300','400','700','900'],
  variable: '--font-lato',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html className="dark" lang="en">
      <body
        className={`${lato.className} antialiased`}
      >
        <ProviderComponent>
        {children}
        <LogoutButton />
        </ProviderComponent>
       
      </body>
    </html>
  );
}
